### ISSUE TITLE
unable to load certificate

### ISSUE THREAD

**Issue by duoleimi** [commandtab/ios-fingerprinter#1]
P12 contains a certificate with SHA-1 fingerprint:
-e   E8:14:A3:4F:73:14:F0:DA:08:77:2F:BE:DE:5F:EC:DE:E6:2A:C8:FC
Attempt to load network entity http://www.apple.com/DTDs/PropertyList-1.0.dtd

Provisioning profile contains 1 developer certificates:
Attempt to load network entity http://www.apple.com/DTDs/PropertyList-1.0.dtd
unable to load certificate

**Comment by command-tab** [comment]
It looks like the `openssl` command has changed somehow in a recent OS X update, breaking the script's ability to extract the certificate from a .p12 file. Investigating...

**Comment by osrufung** [comment]
Same here... any idea?  😕

**Comment by command-tab** [comment]
Should be fixed in `master` now!

Two issues cropped up:
- `xmlstarlet` was doing network requests to load the DTD from Apple, and it (or maybe the Mac sandbox?) was emitting a warning about that. So, that stderr output was directed to `/dev/null` since that's OK.
- `openssl` in later versions of OS X now seems to require base64-encoded certificates to be wrapped at 64 characters. So, I used the `fold` command to wrap the cert data at 64 characters like it expects.

**Comment by osrufung** [comment]
Great, you're my hero! 👏
